# -*- coding: utf-8 -*-
# THE ALLOWLIST, AS A PLAIN LIST, SO THE UPLOAD CHECK CAN USE IT TOO.
#
# The game reads the allowlist straight out of omd1_kit.h, which is generated
# from this machine's own art. The upload check runs somewhere with no game
# installed, so it needs the same set of paths as a flat file.
#
# WHAT THIS PUBLISHES, AND WHAT IT DOES NOT. It writes FILE NAMES - the paths
# the kit generator measured - and nothing else. No mesh data, no textures, no
# geometry, no bytes out of the game's archives. A list of names is not the
# thing the names refer to, and it is the minimum the check needs to be able to
# say "that piece is not real".
#
#   python gen_kit_paths.py ..\omd1_kit.h kit_paths.txt
import io, re, sys

src = sys.argv[1] if len(sys.argv) > 1 else "../omd1_kit.h"
dst = sys.argv[2] if len(sys.argv) > 2 else "kit_paths.txt"

text = io.open(src, encoding="utf-8", errors="replace").read()

# Each row is:  { "label", "art\\...\\thing.vmesh", numbers... }
# The path is the SECOND quoted string on the line, which is what pins this to
# the field rather than to any string that happens to look like a path.
rows = []
for line in text.splitlines():
    line = line.strip()
    if not line.startswith("{"):
        continue
    quoted = re.findall(r'"((?:[^"\\]|\\.)*)"', line)
    if len(quoted) < 2:
        continue
    path = quoted[1].replace("\\\\", "\\")
    if not path:
        continue
    rows.append(path)

seen, out = set(), []
for p in rows:
    k = p.lower()
    if k in seen:
        continue
    seen.add(k)
    out.append(p)

# ---- the markers -----------------------------------------------------------
# A placement can also name a MARKER - "@Rift", "@PlayerStart" and friends -
# and the game resolves those through its own marker table, not the kit. The
# upload check needs the same set or it refuses every playable map. The second
# quoted field of a kMarkerKit row is the proto name.
markers = []
seen_m = set()
src2 = sys.argv[3] if len(sys.argv) > 3 else "../omd1_maps.cpp"
try:
    cpp = io.open(src2, encoding="utf-8", errors="replace").read()
    start = cpp.index("kMarkerKit[] =")
    end = cpp.index("kNumMarkers", start)
    for line in cpp[start:end].splitlines():
        line = line.strip()
        if not line.startswith("{"):
            continue
        q = re.findall(r'"((?:[^"\\]|\\.)*)"', line)
        if len(q) < 2 or not q[1]:
            continue
        k = q[1].lower()
        if k in seen_m:
            continue
        seen_m.add(k)
        markers.append(q[1])
except Exception as e:
    print("WARNING: no markers read from %s (%s)" % (src2, e))

with io.open(dst, "w", encoding="utf-8", newline="\n") as f:
    f.write("# Every piece and marker a shared map is allowed to name.\n")
    f.write("# Generated by gen_kit_paths.py from omd1_kit.h and omd1_maps.cpp.\n")
    f.write("# Do not hand-edit.\n")
    f.write("# These are NAMES ONLY. No game data is in this file.\n")
    f.write("# A line starting with @ is a marker; the editor may append #N to\n")
    f.write("# one to keep several of the same marker apart.\n")
    for p in out:
        f.write(p + "\n")
    for mkr in markers:
        f.write("@" + mkr + "\n")

print("%d piece path(s) + %d marker(s) -> %s" % (len(out), len(markers), dst))
